[package]
name = "doodleray"
version = "5.4.5"
description = "DoodleRay VPN Client"
authors = ["DoodleVPN"]
edition = "2021"
default-run = "DoodleRay"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "DoodleRay"
path = "src/main.rs"

[[bin]]
name = "DoodleRayService"
path = "src/bin/service.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libloading = "0.8"
lazy_static = "1.4"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-updater = "2.10.0"
tauri-plugin-process = "2.3.1"
tauri-plugin-http = "2.5.7"
ctrlc = "3"
keyring = "3"
socket2 = "0.5"
uuid = { version = "1", features = ["v4", "serde"] }

# Windows-only dependencies
[target.'cfg(windows)'.dependencies]
windows-service = "0.7"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Networking_WinInet", "Win32_Security", "Win32_Security_Authorization", "Win32_System_JobObjects", "Win32_System_Pipes", "Win32_System_Threading"] }
winreg = "0.52"
