import type { AppState } from '../stores/app-store';

export function selectDashboardState(state: AppState) {
  return {
    status: state.status,
    setStatus: state.setStatus,
    activeServer: state.activeServer,
    servers: state.servers,
    setActiveServer: state.setActiveServer,
    proxyMode: state.proxyMode,
    setProxyMode: state.setProxyMode,
    systemProxyMode: state.systemProxyMode,
    setSystemProxyMode: state.setSystemProxyMode,
    productMode: state.productMode,
    setRequestModeSwitch: state.setRequestModeSwitch,
    currentDownload: state.currentDownload,
    currentUpload: state.currentUpload,
    addTraffic: state.addTraffic,
    resetTraffic: state.resetTraffic,
    addSpeedPoint: state.addSpeedPoint,
    setCurrentSpeed: state.setCurrentSpeed,
    logs: state.logs,
    addLog: state.addLog,
    clearLogs: state.clearLogs,
    socksPort: state.socksPort,
    httpPort: state.httpPort,
    subscriptions: state.subscriptions,
    updateSubscription: state.updateSubscription,
    autoSelectFastest: state.autoSelectFastest,
    subAutoUpdateMinutes: state.subAutoUpdateMinutes,
    connectedAt: state.connectedAt,
    setConnectedAt: state.setConnectedAt,
    addSubscription: state.addSubscription,
    addServer: state.addServer,
    setSocksPort: state.setSocksPort,
    setHttpPort: state.setHttpPort,
    showStats: state.showStats,
    appSessionDeviceAllowed: state.appSessionDeviceAllowed,
    language: state.language,
  };
}
